### ISSUE TITLE
Can you please provide the paper?

### ISSUE THREAD

**Issue by Dearbreeze** [chenhu96/Self-Supervised-MRI-Reconstruction#1]
Hi! Chenhu
Thanks for you sharing this nice work! 
I want to learn more about your work but I didn't find any .pdf of your paper. 
So can you please provide .pdf of  your paper to me?

I am very grateful for any replies from you!
Best

**Comment by chenhu96** [comment]
> Hi! Chenhu
> Thanks for you sharing this nice work!
> I want to learn more about your work but I didn't find any .pdf of your paper.
> So can you please provide .pdf of your paper to me?
> 
> I am very grateful for any replies from you!
> Best

Thanks for your attention to our work!
It's expected that you cannot retrieve the paper in the database as it has been received but not published.
The paper is likely to be published in the fourth quarter of this year, then you'll be able to retrieve it.
If you are eager to read the more details about this work, you can leave your email address here.
Best!

**Comment by Dearbreeze** [comment]
My email is liudearbreeze@gmail.com
Thanks for you help again
Best!
